### ISSUE TITLE
encode.String16: panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by chenqinghe** [openacid/slim#161]
**Describe the bug**
panic while use encode.String16 as encoder.

**To Reproduce**
```go
func main(){
        keys := []string{"hello"}
	values := []string{"world"}

	st, err := trie.NewSlimTrie(encode.String16{}, keys, values)
	if err != nil {
		panic(err)
	}
	fmt.Println(st.Get("hello"))
}
// output:
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/openacid/slim/encode.String16.GetEncodedSize(...)
        D:/goprojects/pkg/mod/github.com/openacid/slim@v0.5.11/encode/encoder.go
:107
github.com/openacid/slim/trie.(*SlimTrie).getIthLeaf(0xc000004300, 0x0, 0x0, 0x0
)
        D:/goprojects/pkg/mod/github.com/openacid/slim@v0.5.11/trie/slimtrie_que
ry.go:554 +0x65
github.com/openacid/slim/trie.(*SlimTrie).getLeaf(0xc000004300, 0x0, 0x5, 0xc000
000000)
        D:/goprojects/pkg/mod/github.com/openacid/slim@v0.5.11/trie/slimtrie_que
ry.go:544 +0xaf
github.com/openacid/slim/trie.(*SlimTrie).Get(0xc000004300, 0x81866f, 0x5, 0x1, 
0x1, 0x7d2260)
        D:/goprojects/pkg/mod/github.com/openacid/slim@v0.5.11/trie/slimtrie_que
ry.go:59 +0x7c
main.main()
        D:/goprojects/src/test/testtrie/main.go:49 +0x12f
```

**Expected behavior**
works well
**Actual behavior**
panic
**Screenshots**

**Environment (please complete the following information):**
 - OS: windows
 - Version: Windows 10

**Language (please complete the following information):**
 - Language: go
 - Version: go version go1.16.3 windows/amd64

**Comment by drmingdrmer** [comment]
@chenqinghe It's fixed in https://github.com/openacid/slim/commit/b24ed7374aa3a34a11a4826b8203d537b440827a

Now string will be encoded and decoded correctly.

Feel free to re-open it if you have any issue with string values.
